### ISSUE TITLE
some question from this project

### ISSUE THREAD

**Issue by TerrenceFong** [maneeshpal/Drata#1]
Hi! i want to make some business intelligence recently, and i find it in github.
when i download this project to learn, it's too less comment to understand esay.
I don't know nodejs、mongoDB and Knockout, i want to use vuejs refactor it.
Now the biggest problem is when i use `npm run start` to run this project, i can't connect MongoDB, then i install MongoDB, but i don't have this project data. 
If i can connect database, maybe i can refactor it.
So, i think, can i use express-proxy to request `http://drata.io/api` ?
If you can think this issues, can you give me some help?
thanks a lot.

**Comment by maneeshpal** [comment]
[checkout Configuration](https://github.com/maneeshpal/Drata/wiki/Configuration) to see how you can create a config file that the application uses to connect to the database.
You need to have MongoDB instance running before you start the app `npm run start`
That will create a new Database "drataStore" if you haven't created it already. 
For visualizing data, you need to set up another datasource. This could be another database running in the same mongoDB instance. Just create a new database, add a collection and dump some data. You will be able to access the data from drata app to visualize. 
thanks
